
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/* test
*/
import java.util.*;

public class App {
	public String getGreeting() {
		return "Soft2412 Calculator Project Group 13";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
		
		Scanner in = new Scanner(System.in);
		double a, b, c = 0.0;
		
		Calculator calculator = new Calculator();

		System.out.print("Enter the first number: \n");
		a = in.nextDouble();

		System.out.print("And enter second:  \n");
		b = in.nextDouble();

		System.out.print("Choose the operation  " + "\n1.Addition"  +"\n#Please enter the number of operation: \n");
		int input = in.nextInt();
		
		switch (input) {
			case 1 :
				c = calculator.Addition(a,b);
				System.out.println(a + " + " + b + " = " + c);
				break; 
			case 2 :
				c = calculator.Subtraction(a,b);
				System.out.println(a + " - " + b + " = " + c);
				break;
			default:
				System.out.println("invalid selection");
		}

	}
}
