/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    
    @Test
    public void testAddition(){
    	App additionTest = new App();
    	double c=11.0;
    	double a=5.0;
    	double b=6.0;
    	double d=12.0;
    	
    	//assertEquals(c, additionTest.Addition(a,b));
    	//assertNotEquals(d, additionTest.Addition(a,b));
    }
}
